### ISSUE TITLE
namedAccounts is undefined

### ISSUE THREAD

**Issue by travisdmathis** [wighawag/buidler-deploy#4]
```
require('dotenv').config();

usePlugin("@nomiclabs/buidler-waffle");
usePlugin("@nomiclabs/buidler-ethers");
usePlugin("@nomiclabs/buidler-etherscan");
usePlugin("buidler-deploy");
usePlugin("solidity-coverage");

const ETHERSCAN_API_KEY = process.env.ETHERSCAN || "";

module.exports = {
  namedAccounts: {
    deployer: {
      default: 0
    },
  },
  defaultNetwork: "buidlerevm",
  solc: {
    version: "0.6.6",
    optimizer: {
      runs: 200,
      enabled: true,
    }
  },
  networks: {
    buidlerevm: {
      gasPrice: 0,
      blockGasLimit: 100000000,
    },
    coverage: {
      url: 'http://127.0.0.1:8555' // Coverage launches its own ganache-cli client
    }
  },
  etherscan: {
    url: "https://api.etherscan.io/api",
    apiKey: ETHERSCAN_API_KEY
  },
  paths: {
    deploy: 'deploy',
    deployments: 'deployments'
  }
};
```
```
module.exports = async ({ namedAccounts, deployments }) => {
  const { deployIfDifferent, log } = deployments;
  console.log('**** namedAccounts ***', namedAccounts);

  const { deployer } = namedAccounts;

  console.log('**** AGENT ***', namedAccounts);

  const storage = await deployIfDifferent('data', 'EternalStorage', { from: deployer }, 'EternalStorage')

  if (storage.newlyDeployed) {
    log(`contract Storage has been deployed: ${storage.address}`);
  }
}
module.exports.tags = ['EternalStorage'];
```

```
All contracts have already been compiled, skipping compilation.
**** namedAccounts *** undefined
An unexpected error occurred:

Error: ERROR processing /mnt/f/projects/PanDAO/pandao-contracts/deploy/eternalStorage.js:
TypeError: Cannot destructure property `deployer` of 'undefined' or 'null'.
    at Object.module.exports [as func] (/mnt/f/projects/PanDAO/pandao-contracts/deploy/eternalStorage.js:5:24)
    at DeploymentsManager.runDeploy (/mnt/f/projects/PanDAO/pandao-contracts/node_modules/buidler-deploy/src/DeploymentsManager.ts:557:32)
    at SimpleTaskDefinition.config_1.internalTask.addOptionalParam.addOptionalParam.addOptionalParam.addOptionalParam.setAction [as action] (/mnt/f/projects/PanDAO/pandao-contracts/node_modules/buidler-deploy/src/index.ts:91:33)
    at Environment._runTaskDefinition (/mnt/f/projects/PanDAO/pandao-contracts/node_modules/@nomiclabs/buidler/src/internal/core/runtime-environment.ts:197:35)
    at Environment.run (/mnt/f/projects/PanDAO/pandao-contracts/node_modules/@nomiclabs/buidler/src/internal/core/runtime-environment.ts:122:17)
    at SimpleTaskDefinition.config_1.task.addOptionalParam.addOptionalParam.setAction [as action] (/mnt/f/projects/PanDAO/pandao-contracts/node_modules/buidler-deploy/src/index.ts:104:17)
    at DeploymentsManager.runDeploy (/mnt/f/projects/PanDAO/pandao-contracts/node_modules/buidler-deploy/src/DeploymentsManager.ts:560:19)
```

**Comment by wighawag** [comment]
Hi, thanks for the report.
namedAccounts has now been renamed to `getNamedAccount` that return a promise instead. This allow it to work in scripts without needing to use the buidler command

So this would become:
```
module.exports = async ({ getNamedAccounts, deployments }) => {
  const { deployIfDifferent, log } = deployments;
  const namedAccounts = await getNamedAccounts();
  console.log('**** namedAccounts ***', namedAccounts);

  const { deployer } = namedAccounts;

  console.log('**** AGENT ***', namedAccounts);

  const storage = await deployIfDifferent('data', 'EternalStorage', { from: deployer }, 'EternalStorage')

  if (storage.newlyDeployed) {
    log(`contract Storage has been deployed: ${storage.address}`);
  }
}
module.exports.tags = ['EternalStorage'];
```

**Comment by wighawag** [comment]
I updated the doc : https://github.com/wighawag/buidler-deploy/commit/8e03e418dec2cef368b13d45e7a5cf71acfa8147

**Comment by travisdmathis** [comment]
thanks @wighawag -- absolutely love the plugin.. what a huge employment to my last projects deployment scripts!
